### PR TITLE
Update profile to match CIS v1.1.0 (v2)

### PR DESCRIPTION
**Pull request by fatbasstard**
The original PR with the update to CiS 1.1.0 is dropped a month ago but there has been no feedback from the author of that PR @itoperatorguy 

We ourself hit another CiS 1.1.0 issue and to keep thing moving I grabbed the commits from @itoperatorguy , added my missing feature (check on `/etc/passwd` is changed from `0600` to `0644` or more restrictive) and processed the feedback on the original PR.

### CODE REVIEW

**Comment by itoperatorguy** [comment]
Hi,

Sorry for the late reply. I worked on some internal stuffs lately + I was on a longer PTO. Please let me know how can I help you at this stage.

**Comment by fatbasstard** [comment]
Hi @itoperatorguy !

Glad you're back. Well, in short I'd love to get the 1.1.0 CIS implementation enabled in this repo. Best approach perhaps is if you get update your (original) PR.

If you're time restricted, I can try to get your changes in with this PR

**Comment by fatbasstard** [comment]
I'l close this 2. Too many changes and merge errors caused by the https://github.com/dev-sec/cis-dil-benchmark/pull/55/files

Only way I can easily fix this is by recoding the changed, merging code is drama...

**Comment by itoperatorguy** [comment]
I would wait for a few weeks. I mean InSpec 3.0 has just been released. They will do some base demo on November 1st. Maybe it will worth to check it out and upgrade the code to CIS 1.1.0 and InSpec 3.0 compatible.

What do you think?

**Pull request closed without merging**
