### PR TITLE
CIS DIL Benchmark V2

### PR DESCRIPTION
**Pull request by deric4**
Updates to InSpec style guide recommendations and version 2 of the CIS DIL Benchmark

### CODE REVIEW

**Comment by micheelengronne** [comment]
Thank you @deric4 

Can you solve the coding styles problems detected by rubocop ?

**Review by micheelengronne — CHANGES_REQUESTED** [review]
I would prefer not to disable linter checks globally but only where it is absolutely needed. Can you [disable in source code](https://docs.rubocop.org/rubocop/configuration.html#disabling-cops-within-source-code) instead ? @chris-rock what do you think ?

**Comment by deric4** [comment]
> I would prefer not to disable linter checks globally but only where it is absolutely needed. Can you [disable in source code](https://docs.rubocop.org/rubocop/configuration.html#disabling-cops-within-source-code) instead ?

Hi @micheelengronne ! Ya can def do that if you'd like, but not sure if you saw the reasoning in the latest commit message:

>   Inspec Style Guide suggests avoiding in matchers
>   - https://docs.chef.io/inspec/style/#avoid-unnecessary-parentheses-in-matchers
> 
>   Examples in the documentation
>   - https://docs.chef.io/inspec/matchers/#match
>   - https://docs.chef.io/inspec/dsl_inspec/#test-if-mysql-passwords-are-in-env
>   - https://docs.chef.io/inspec/dsl_inspec/#interactive-debugging-with-pry

Appreciate the feedback!  😄

**Comment by micheelengronne** [comment]
You are right. There is a conflict of conventions here. @chris-rock is the arbitrator. Do we stick to the Chef convention or the rubocop one ?

**Comment by micheelengronne** [comment]
As the Inspec convention is followed, I will merge it. If we have to change the convention, we can do it after.

**Pull request merged**
