### PR TITLE
Passwords to password

### PR DESCRIPTION
**Pull request by crashdummymch**
This changes the passwords to password as defined in the inspec documentation:
https://www.inspec.io/docs/reference/resources/shadow/

### CODE REVIEW

**Comment by chris-rock** [comment]
Thank you @crashdummymch for your contribution. I'd like to get #9 in first, so that we have additional rubocop and inspec check in before we merge your.

**Comment by chris-rock** [comment]
fixes #5

**Comment by crashdummymch** [comment]
will rebase and re-submit

**Comment by crashdummymch** [comment]
this is a fix for #5

**Comment by chris-rock** [comment]
Thank you @crashdummymch for your first contribution to this repository!

**Pull request merged**
