### PR TITLE
motd may be configured under /etc/update-motd.d/

### LINKED ISSUE #125: /etc/motd should skip permissions check if file doesn't exist
**Describe the bug**
We've been getting Inspec reports about the `/etc/motd` permissions from this section here: https://github.com/dev-sec/cis-dil-benchmark/blob/master/controls/1_7_warning_banners.rb#L61-L74

However in most of our VMs, we do not have an `/etc/motd` file. The inspec message is:

```
expected: "root"
     got: nil

(compared using ==)
```

I would think the check should just skip if the file doesn't exist. It's certainly not a security issue.

**Expected behavior**
Exit/skip and move on to the next check

**Actual behavior**

```
0 {
code_desc   File /etc/motd group is expected to eq "root"
message
expected: "root"
     got: nil

(compared using ==)
resource_class  file
resource_params ["/etc/motd"]
run_time    0.000364499
start_time  2022-06-16T03:59:19+00:00
status  failed
},
1 {
code_desc   File /etc/motd owner is expected to eq "root"
message
expected: "root"
     got: nil

(compared using ==)
resource_class  file
resource_params ["/etc/motd"]
run_time    0.000201999
start_time  2022-06-16T03:59:19+00:00
status  failed
},
2 {
code_desc   File /etc/motd mode is expected to cmp == "0644"
message
expected: 0644
     got:

(compared using `cmp` matcher)
resource_class  file
resource_params ["/etc/motd"]
run_time    0.000698698
start_time  2022-06-16T03:59:19+00:00
status  failed
}
```

**Example code**

```
/opt/chef/embedded/bin/inspec exec https://github.com/dev-sec/cis-dil-benchmark/archive/master.zip --reporter=json
```

**OS / Environment**

* Ubuntu Linux 18.04 in Azure (5.4.0-1083-azure)

```
$ uname -rvmpis
Linux 5.4.0-1083-azure #87~18.04.1-Ubuntu SMP Fri Jun 3 13:19:07 UTC 2022 x86_64 x86_64 x86_64
```

**Inspec Version**

```
4.46.13
```

**Baseline Version**
Whatever is in https://github.com/dev-sec/cis-dil-benchmark/archive/master.zip

**Additional context**

### PR DESCRIPTION
**Pull request by bendres97**
Signed-off-by: bendres97<bryan@endres.io>

Fixes #125

Added a check to only run tests on /etc/motd if it exists.

Added additional logic to validate any motd files under /etc/update-motd.d/

### CODE REVIEW

**Comment by Spencer-Doak** [comment]
I'm not familiar with `/etc/update-motd.d/`, so apologies if this is a noob question, but why would the files under `/etc/update-motd.d/` have 0755 permissions, when `/etc/motd` is expected to have 0644 permissions?

**Comment by bendres97** [comment]
The files under the directory are excutable scripts so they need the executable bitSent from my Galaxy
-------- Original message --------From: Spencer ***@***.***> Date: 6/29/22  11:07  (GMT-06:00) To: dev-sec/cis-dil-benchmark ***@***.***> Cc: Bryan Endres ***@***.***>, Author ***@***.***> Subject: Re: [dev-sec/cis-dil-benchmark] motd may be configured under /etc/update-motd.d/ (PR #127) 
I'm not familiar with /etc/update-motd.d/, so apologies if this is a noob question, but why would the files under /etc/update-motd.d/ have 0755 permissions, when /etc/motd is expected to have 0644 permissions?

**Comment by dtseiler** [comment]
Poking my head in to see if it's possible to get this merged. I see it's failing lint tests on:

```
controls/1_7_warning_banners.rb:71:11: W: [Correctable] Lint/DeprecatedClassMethods: File.exists? is deprecated in favor of File.exist?.
  if File.exists?(motd_file)
```

**Comment by bendres97** [comment]
Good catch, I will see about updating this when I get some cycles. Sent from my Galaxy
-------- Original message --------From: Don Seiler ***@***.***> Date: 9/15/22  09:49  (GMT-06:00) To: dev-sec/cis-dil-benchmark ***@***.***> Cc: Bryan Endres ***@***.***>, Author ***@***.***> Subject: Re: [dev-sec/cis-dil-benchmark] motd may be configured under /etc/update-motd.d/ (PR #127) 
Poking my head in to see if it's possible to get this merged. I see it's failing lint tests on:
controls/1_7_warning_banners.rb:71:11: W: [Correctable] Lint/DeprecatedClassMethods: File.exists? is deprecated in favor of File.exist?.
  if File.exists?(motd_file)

**Comment by bendres97** [comment]
I horked this up pretty bad... I'll open a new PR

**Pull request closed without merging**
