### PR TITLE
1.1 updates to match benchmark v2

### PR DESCRIPTION
**Pull request by deric4**

### CODE REVIEW

**Comment by micheelengronne** [comment]
@deric4 you closed the issue. Are you not satisfied of it ? To push the profile to `v2` is interesting.

**Comment by micheelengronne** [comment]
Related https://github.com/dev-sec/cis-dil-benchmark/issues/67

**Comment by flyinbutrs** [comment]
Hi @micheelengronne - Logicworks is starting to update this inspec profile to DIL benchmark v2.0.0 for our own internal processes, and were planning to offer the end result as a PR. I suspect it'd be better to have a full PR with all 2.0.0 changes rather than having section by section PRs. 

Thanks for pointing out #67, we'll try applying those patches and evaluate how close those get.

Some questions:

1. Is it safe to assume there's no need for side-by-side support for both `v1.x.x` and `v2.x.x` versions of the CIS DIL specification?

1. Is there any contribution guidelines (aside from apache license)?

1. Would it be preferable to have it in one PR for all controls?

**Comment by chris-rock** [comment]
@flyinbutrs That is awesome. Thank you.

1. Since 2.0.0 is superseding 1.0.0, there is no need to support both version.

2. All contributions are apache licensed and they need to be signed-off, that's all

3. It depends. I assume it there are quite some changes. If those changes are non-breaking, we can merge them along the way.

**Pull request closed without merging**
